name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Test build
        run: pnpm generate
        env:
          NUXT_PUBLIC_PREZ_API_ENDPOINT: ${{ vars.DEV_ENDPOINT }} 